In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,5,7], dtype='i')

In [16]:
b = np.array([2,3,5], dtype='f')

In [17]:
print(a, type(a))

[1 2 3 5 7] <class 'numpy.ndarray'>


In [18]:
type(b)

numpy.ndarray

In [19]:
a.dtype
#this tells us the datatype

dtype('int32')

In [21]:
b.dtype

dtype('float32')

In [22]:
a=np.array([[1,2,3], [4,5,6]])
#dimenstion of array=total number of indeces required to access an individual element of the array

In [23]:
print(a.ndim)
#number of dimensions

2


In [25]:
print(a[0,2])

3


In [30]:
b = np.array([[1,2,3],[2,4,5],[5,6,9]])

In [32]:
print(b[0,2])
b.ndim

3


2

In [34]:
print(b[1,2])

5


In [5]:
C = np.array([[[1,2,3], [4,5,6], [0,0,-1]], [[-1,-2,-3], [-4,-5,-6], [0,0,-1]]])

In [6]:
C.ndim

3

In [7]:
print(C[1,0,2])

-3


In [8]:
type(C)

numpy.ndarray

In [9]:
print(C)

[[[ 1  2  3]
  [ 4  5  6]
  [ 0  0 -1]]

 [[-1 -2 -3]
  [-4 -5 -6]
  [ 0  0 -1]]]


In [11]:
print(C.shape)
#returns a turple
# 2- number of 2d arrays
# 3- number of 1d arrays in each 2d array
#3- number of items in each 1d array

(2, 3, 3)


In [13]:
C.shape[0]

2

In [15]:
A = np.array([2])

In [16]:
A.ndim

1

In [17]:
B = np.array(3)
#this is a 0d array since it hasnt been passed as a list just a number

In [18]:
B.ndim

0

In [19]:
C.size

18

In [20]:
C.nbytes

144

In [24]:
A = np.arange(100)
#simply create an array with all numbers from 0-100-1

In [25]:
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [30]:
B = np.arange(20, 101, 3)
#seems like the for i in range(20, 100, 3)

In [31]:
print(B)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [32]:
#range is an iterator
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [33]:
D = np.random.permutation(np.arange(10))
# arange returns 10 elements 0- 9
# permutation shufles the elements 

In [34]:
print(D)

[5 2 1 6 4 0 3 8 7 9]


In [35]:
np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik